# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
variables:
  configuration: debug
  platform: x64

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '16.15.1'
  displayName: 'Install Node.js'

- script: |
    yarn
  displayName: 'install js packages'


- task: Gradle@3
  inputs:
    workingDirectory: 'android'
    gradleWrapperFile: 'android/gradlew'
    tasks: 'bundleRelease'
    javaHomeOption: 'JDKVersion'
  continueOnError: false
  displayName: "Compile apk bundleRelease"
  

- script: ls android/app/build/outputs/bundle/release
  displayName: Android Postprocess
  continueOnError: false

- task: AndroidSigning@2
  displayName: "Signing android apk"
  inputs:
    apkFiles: 'android/app/build/outputs/bundle/release/*.aab'
    jarsign: true 
    jarsignerKeystoreFile: 'my-upload-key.keystore'
    jarsignerKeystorePassword: '1234567890'
    jarsignerKeystoreAlias: 'my-key-alias'
    jarsignerKeyPassword: '1234567890'
    jarsignerArguments: '-sigalg SHA256withRSA -digestalg SHA-256'
    zipalign: true

- task: CopyFiles@2
  inputs:
    contents: '**/*.aab'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: ms-vsclient.google-play.google-play-status-update.GooglePlayStatusUpdate@2
  displayName: 'Update com.ci_cd_test status to completed'
  inputs:
    serviceConnection: test
    packageName: 'com.ci_cd_test'
    track: internal
    status: completed
    # userFraction: "0.99"